name: air-quality-express
org: chenseanxy
app: air-quality
stage: dev
component: express

inputs:
  src:
    src: ./
    exclude:
      - .env
      - serverless.yml
  region: ${env:REGION}
  runtime: Nodejs10.15
  functionName: ${app}-express
  serviceName: air_quality_gateway
  serviceId: service-0gxcokmg
  functionConf:
    timeout: 15
    environment:
      variables:
        BAIDU_AK: ${env:BAIDU_AK}
        PORT: 80
    vpcConfig:
      vpcId: ${output:${stage}:${app}:${app}-vpc.vpcId}
      subnetId: ${output:${stage}:${app}:${app}-vpc.subnetId}
  apigatewayConf:
    isDisabled: true
