name: air-quality-express
org: air-quality
app: air-quality
stage: dev
component: express

inputs:
  src:
    src: ./
    exclude:
      - .env
      - serverless.yml
  region: ${env:REGION}
  runtime: Nodejs10.15
  apigatewayConf:
    protocols:
      - https
    environment: release
