name: air-quality-vue
org: chenseanxy
app: air-quality
stage: dev
component: website

inputs:
  src:
    src: ./src
    exclude:
      - .env
      - serverless.yml
    dist: ./dist
    hook: npm run build
    index: index.html
    error: index.html
  region: ${env:REGION}
  bucketName: ${env:BUCKET}
  protocol: http
